// Contenido del área contable.
export const accounting = {
  slug: 'contable',
  eyebrow: 'Área Contable',
  hero: {
    titleLine1: 'Contabilidad e impuestos,',
    titleLine2: '25 años de oficio.',
    lead:
      'Área contable del estudio, integrada al equipo legal — en Argentina y en operaciones internacionales.',
    ctaPrimary: 'Solicitar consulta',
  },
  counters: {
    label: 'En cifras',
    title: 'El área contable en números',
    sub: 'Veinticinco años acompañando con números que se sostienen.',
    items: [
      { num: '25', suffix: '',   label: 'Años de trayectoria',    desc: 'Veinticinco años de asesoramiento contable e impositivo a empresas y grupos familiares.', icon: 'clock' },
      { num: '6',  suffix: '',   label: 'Servicios centrales',    desc: 'Impuestos, estados contables, auditoría, planificación, sueldos y contabilidad internacional.', icon: 'book' },
      { num: '3',  suffix: '',   label: 'Jurisdicciones activas', desc: 'Sede en Buenos Aires, con corresponsalías en distintos países para operaciones transfronterizas.', icon: 'globe' },
      { num: '100',suffix: '%',  label: 'Integración legal',      desc: 'Coordinación permanente con el equipo jurídico — soluciones contables y legales bajo el mismo mandato.', icon: 'link' },
    ],
  },
  practice: {
    label: 'Servicios contables',
    title: 'Servicios',
    sub: 'Cobertura completa de las necesidades contables e impositivas de la empresa.',
    items: [
      {
        key: 'impuestos',
        name: 'Liquidación de Impuestos',
        desc: 'Liquidación mensual y anual de IVA, Ganancias, Ingresos Brutos, Bienes Personales, retenciones y percepciones.',
        meetingTopic: 'liquidación de impuestos',
        intro: 'La liquidación impositiva es la base operativa del cumplimiento fiscal. Acompañamos a empresas y monotributistas en sus presentaciones de IVA, Ganancias, Bienes Personales, Ingresos Brutos y demás obligaciones nacionales y provinciales — con foco en evitar intereses, multas y discrepancias con ARCA.',
        services: [
          { title: 'IVA mensual',                     desc: 'Liquidación y presentación de la DJ F.731, gestión del crédito fiscal y débitos por dígito CUIT.' },
          { title: 'Anticipos y DJ anual de Ganancias', desc: 'Cálculo de anticipos según el régimen general, ajustes por inflación y presentación de DJ anual F.713/F.711.' },
          { title: 'Ingresos Brutos y Convenio Multilateral', desc: 'Liquidación de IIBB en CABA y provincias, Convenio Multilateral CM05 y CM03, regímenes de retención y percepción.' },
          { title: 'Bienes Personales',               desc: 'DJ y pago como persona física o como responsable sustituto por participaciones societarias (F.762/F.763).' },
          { title: 'Retenciones y percepciones',      desc: 'Régimen SICORE, SIRE, retenciones de Ganancias, IVA y SUSS sobre proveedores y empleados.' },
          { title: 'Monotributo y recategorizaciones',desc: 'Inscripción, pago mensual unificado y recategorización semestral en enero y julio.' },
        ],
      },
      {
        key: 'estados',
        name: 'Estados Contables',
        desc: 'Preparación de estados contables anuales e intermedios bajo NIIF y normas profesionales argentinas.',
        meetingTopic: 'estados contables',
        intro: 'La preparación de estados contables requiere conocimiento profundo de las normas contables argentinas y NIIF. Elaboramos balances anuales, intermedios y especiales, listos para presentar ante ARCA, IGJ, bancos, inversores o terceros interesados.',
        services: [
          { title: 'Estados anuales',                 desc: 'Balance general, estado de resultados, evolución del patrimonio neto y flujo de efectivo bajo normas profesionales argentinas (RT FACPCE).' },
          { title: 'Estados bajo NIIF (IFRS)',        desc: 'Preparación bajo Normas Internacionales de Información Financiera para empresas con casa matriz extranjera o que cotizan.' },
          { title: 'Estados intermedios',             desc: 'Trimestrales o semestrales para uso gerencial, presentación a bancos o reportes a inversores.' },
          { title: 'Estados especiales',              desc: 'Para fusiones, escisiones, reorganizaciones societarias y procedimientos concursales.' },
          { title: 'Memoria y notas explicativas',    desc: 'Redacción de la memoria del directorio y notas a los estados conforme las exigencias legales y profesionales.' },
          { title: 'Presentación ante IGJ',           desc: 'Armado y presentación de la documentación anual ante la Inspección General de Justicia y registros provinciales.' },
        ],
      },
      {
        key: 'auditoria',
        name: 'Auditoría Contable',
        desc: 'Auditoría de estados financieros, revisiones limitadas, procedimientos acordados y due diligence contable.',
        meetingTopic: 'auditoría contable',
        intro: 'La auditoría externa da credibilidad a los números de la empresa frente a inversores, bancos, socios y autoridades. Trabajamos bajo normas de auditoría argentinas (RT 37) e internacionales (ISA), con un enfoque centrado en la materialidad y el riesgo del negocio.',
        services: [
          { title: 'Auditoría de estados financieros',desc: 'Examen completo conforme RT 37 / ISA, con emisión de dictamen para uso público o privado.' },
          { title: 'Revisiones limitadas',            desc: 'Procedimientos analíticos e indagaciones para estados intermedios, sin alcance de auditoría completa.' },
          { title: 'Procedimientos acordados',        desc: 'Trabajo a medida sobre rubros o transacciones específicas, según los términos pactados con el cliente.' },
          { title: 'Due diligence contable',          desc: 'Revisión integral previa a operaciones de M&A, financiamiento o cambios accionarios — con foco en riesgos contables y fiscales.' },
          { title: 'Auditoría interna',               desc: 'Diagnóstico y diseño de controles internos para empresas que requieren un esquema robusto de governance contable.' },
          { title: 'Informes especiales',             desc: 'Certificaciones para subsidios, reintegros, licitaciones, financiamiento y otras instancias específicas.' },
        ],
      },
      {
        key: 'planificacion',
        name: 'Planificación Impositiva',
        desc: 'Estructuración fiscal, análisis de carga tributaria, reorganizaciones empresariales y precios de transferencia.',
        meetingTopic: 'planificación impositiva',
        intro: 'La planificación fiscal busca reducir la carga impositiva dentro del marco legal — anticipándose a obligaciones, optimizando la estructura del negocio y aprovechando regímenes promocionales. Trabajamos en coordinación con el área legal del estudio para abordar tanto la dimensión contable como la jurídica.',
        services: [
          { title: 'Estructuración fiscal',           desc: 'Diseño de estructuras societarias y de tenencia para minimizar la carga tributaria global manteniendo cumplimiento.' },
          { title: 'Análisis de carga tributaria',    desc: 'Modelado de la carga fiscal efectiva por jurisdicción, impuesto y rubro de actividad, con escenarios proyectados.' },
          { title: 'Reorganizaciones empresariales',  desc: 'Fusiones, escisiones y transferencias bajo el régimen de reorganización fiscal del art. 80 LIG, sin impacto impositivo.' },
          { title: 'Precios de transferencia',        desc: 'Estudios para operaciones con vinculadas del exterior — análisis funcional, comparables y memorando descriptivo.' },
          { title: 'Regímenes promocionales',         desc: 'Acceso y cumplimiento de regímenes como Conocimiento, Economía del Conocimiento y zonas francas.' },
          { title: 'Consultas vinculantes',           desc: 'Presentación de consultas ante ARCA y respuesta a inspecciones con sustento técnico documentado.' },
        ],
      },
      {
        key: 'sueldos',
        name: 'Liquidación de Sueldos',
        desc: 'Liquidación de haberes, cargas sociales, aportes y contribuciones. Presentación de DJ ante ARCA.',
        meetingTopic: 'liquidación de sueldos',
        intro: 'La liquidación de sueldos no es solo calcular un haber bruto: implica conocer convenios colectivos, calcular cargas sociales, retenciones de Ganancias 4ta categoría, y presentar las DJ correspondientes — todo en plazo para evitar contingencias laborales y fiscales.',
        services: [
          { title: 'Liquidación mensual de haberes',  desc: 'Cálculo de sueldos brutos, descuentos, asignaciones familiares y entrega de recibos según el convenio aplicable.' },
          { title: 'Cargas sociales (SIPA, OS, ART)', desc: 'Cálculo y presentación de la DJ F.931, pago de aportes y contribuciones a SIPA, obra social y ART.' },
          { title: 'Retención de Ganancias 4ta',      desc: 'Cálculo mensual de la retención del impuesto sobre haberes, ajustes anuales y presentación del SIRADIG.' },
          { title: 'Liquidación de SAC y vacaciones', desc: 'Cálculo del aguinaldo (SAC) en junio y diciembre, vacaciones, licencias y demás conceptos no remunerativos.' },
          { title: 'Indemnizaciones y desvinculaciones', desc: 'Cálculo y certificación de indemnizaciones por despido, art. 245 LCT, gratificaciones y entrega de Form. 985 / 5072.' },
          { title: 'DJ y declaraciones laborales',    desc: 'F.931 mensual, F.572 anual, F.649 final, libro de sueldos digital y demás obligaciones del empleador.' },
        ],
      },
      {
        key: 'internacional',
        name: 'Contabilidad Internacional',
        desc: 'Asesoramiento para empresas con operaciones en el exterior. Consolidación NIIF y conversión de moneda.',
        meetingTopic: 'contabilidad internacional',
        intro: 'Empresas con operaciones transfronterizas necesitan estados consolidados, conversión de moneda y reportes que cumplan con normativas locales y de la casa matriz. Trabajamos con corresponsalías en distintos países para coordinar requerimientos en cada jurisdicción.',
        services: [
          { title: 'Consolidación NIIF',              desc: 'Eliminación de operaciones intercompañía, ajustes de consolidación y armado del balance consolidado del grupo bajo IFRS.' },
          { title: 'Conversión de moneda',            desc: 'Conversión de estados contables locales a moneda funcional o de presentación, conforme NIC 21.' },
          { title: 'Reportes a casa matriz',          desc: 'Armado de paquetes de reporte mensuales/trimestrales con el formato y los GAAP requeridos por la matriz extranjera.' },
          { title: 'Análisis de tax provisión',       desc: 'Provisión de impuestos diferidos, cálculo del effective tax rate y reconciliación con la liquidación local.' },
          { title: 'Operaciones con vinculadas',      desc: 'Documentación de operaciones intercompañía, contratos intra-grupo y soporte para el estudio de precios de transferencia.' },
          { title: 'Asistencia a inversiones extranjeras', desc: 'Asesoramiento contable a empresas extranjeras que se instalan en Argentina — desde el setup inicial hasta la operación regular.' },
        ],
      },
    ],
  },
  team: {
    label: 'Equipo contable',
    title: 'Contadores públicos matriculados.',
    sub: 'Cada cliente tiene un contador responsable que conoce la operación en detalle, en coordinación permanente con el área legal.',
    members: [
      { key: 'responsable-contable',    initials: 'CP', name: 'Responsable contable',     role: 'Responsable del Área',    spec: 'Impuestos · Auditoría · Estados Contables',          photo: '/team-contable/responsable.jpg' },
      { key: 'especialista-impositivo', initials: 'EI', name: 'Especialista impositivo',  role: 'Especialista Impositivo', spec: 'Planificación Fiscal · Precios de Transferencia',    photo: '/team-contable/especialista.jpg' },
    ],
    ctaText: '',
  },
  timeline: {
    label: 'Trayectoria',
    title: 'Trayectoria',
    items: [
      { year: '2001', title: 'Fundación del estudio', desc: 'Se constituye Pantarotto Lértora & Asocs.' },
      { year: '2010', title: 'Red internacional',     desc: 'Apertura de corresponsalías contables en distintos países.' },
      { year: '2015', title: 'Servicios aduaneros',   desc: 'Incorporación de liquidación aduanera, reintegros y devolución de IVA.' },
      { year: '2020', title: 'División autónoma',     desc: 'Consolidación del área contable como práctica propia.' },
      { year: '2026', title: '25 años',               desc: 'Veinticinco años de asesoramiento impositivo y contable.' },
    ],
  },
  contact: {
    label: 'Contacto',
    title: 'Hablemos de',
    titleAccent: 'su situación',
    desc: 'Nuestro equipo contable le brinda una consulta inicial para evaluar sus necesidades y proponer el servicio más adecuado.',
    formAreas: ['Liquidación de Impuestos', 'Estados Contables', 'Auditoría', 'Planificación Impositiva', 'Sueldos', 'Contabilidad Internacional', 'Otro'],
  },
};
