// Contenido del área legal (abogados).
export const legal = {
  slug: '',
  eyebrow: 'Área Legal',
  hero: {
    titleLine1: 'Derecho empresarial,',
    titleLine2: '23 años de práctica.',
    lead:
      'Estudio de abogados con sede en Buenos Aires y corresponsalías en distintos países.',
    ctaPrimary: 'Solicitar consulta',
  },
  counters: {
    label: 'En cifras',
    title: 'El estudio en números',
    sub: 'Dos décadas de trabajo continuo, con foco y método.',
    items: [
      { num: '20', suffix: '+',  label: 'Años de trayectoria',  desc: 'Dos décadas asesorando a empresas en operaciones tributarias, societarias y penales económicas complejas.', icon: 'clock' },
      { num: '5',  suffix: '',   label: 'Áreas especializadas', desc: 'Tributario, laboral, societario, aerocomercial y penal económico.', icon: 'layers' },
      { num: '3',  suffix: '',   label: 'Jurisdicciones',       desc: 'Sede en Buenos Aires, con corresponsalías activas en distintos países.', icon: 'globe' },
      { num: '100',suffix: '%',  label: 'Confidencialidad',     desc: 'Secreto profesional y reserva estricta sobre toda la información del cliente.', icon: 'shield' },
    ],
  },
  practice: {
    label: 'Práctica profesional',
    title: 'Áreas',
    sub: 'Cinco áreas de derecho empresarial, ejercidas con autonomía y coordinación entre sí.',
    items: [
      {
        key: 'tributario',
        name: 'Tributario',
        desc: 'Planificación fiscal, litigios ante el fisco, precios de transferencia, tributario internacional y reestructuraciones impositivas.',
        meetingTopic: 'derecho tributario',
        intro: 'El derecho tributario regula la relación entre los contribuyentes y el fisco. Asesoramos a empresas y grupos económicos en la planificación de su carga fiscal, la defensa ante inspecciones y reclamos de ARCA-DGI y los fiscos provinciales, y la estructuración de operaciones complejas que impactan en impuestos nacionales, provinciales y municipales.',
        services: [
          { title: 'Planificación fiscal',        desc: 'Diseño de estructuras impositivas eficientes para empresas locales e internacionales, en cumplimiento con la normativa vigente.' },
          { title: 'Litigios ante el fisco',      desc: 'Defensa en procedimientos de determinación de oficio, recursos administrativos y acciones contencioso-tributarias en todas las instancias.' },
          { title: 'Precios de transferencia',    desc: 'Estudio y documentación de operaciones entre empresas vinculadas, con foco en BEPS y los lineamientos OCDE.' },
          { title: 'Tributación internacional',   desc: 'Análisis de convenios para evitar la doble imposición, residencia fiscal de personas físicas y jurídicas, e impuestos por inversiones extranjeras.' },
          { title: 'Reestructuraciones impositivas', desc: 'Reorganizaciones societarias con tratamiento fiscal — fusiones, escisiones, transferencias de fondos de comercio, sin pérdida de quebrantos ni cómputos pendientes.' },
        ],
      },
      {
        key: 'laboral',
        name: 'Laboral',
        desc: 'Relaciones individuales y colectivas de trabajo, negociación sindical, conflictos laborales y reestructuraciones de personal.',
        meetingTopic: 'derecho laboral',
        intro: 'Asesoramos en relaciones individuales y colectivas de trabajo, conflictos laborales, negociación con sindicatos y reestructuraciones de personal. Defensa empresarial en juicios laborales y prevención de contingencias por despidos, accidentes y reclamos sindicales.',
        services: [
          { title: 'Relaciones individuales',     desc: 'Contratos de trabajo, despidos con y sin causa, indemnizaciones, sanciones disciplinarias y modificaciones contractuales.' },
          { title: 'Relaciones colectivas',       desc: 'Negociación de convenios colectivos, paritarias, conflictos sindicales y procedimientos de conciliación obligatoria.' },
          { title: 'Negociación sindical',        desc: 'Acuerdos de empresa con representaciones gremiales, soluciones de conflictos colectivos y manejo de medidas de fuerza.' },
          { title: 'Conflictos laborales',        desc: 'Defensa en juicios por despidos, ART, seguros laborales, accidentes y enfermedades profesionales.' },
          { title: 'Reestructuraciones de personal', desc: 'Programas de retiro voluntario, suspensiones, traslados y modificaciones contractuales en contextos de crisis o transformación.' },
        ],
      },
      {
        key: 'societario',
        name: 'Societario',
        desc: 'Gobierno corporativo, fusiones y adquisiciones, due diligence, acuerdos de accionistas y transformaciones societarias.',
        meetingTopic: 'derecho societario',
        intro: 'Cubrimos todo el ciclo de vida societario: constitución, gobierno corporativo, fusiones y adquisiciones, due diligence y reorganizaciones. Asesoramos a accionistas, directores y comités en sus deberes, derechos y conflictos, y acompañamos transacciones complejas con corresponsalías en distintos países.',
        services: [
          { title: 'Gobierno corporativo',        desc: 'Deberes fiduciarios, reglamentos internos, políticas de governance, comités de auditoría y prácticas de buen gobierno.' },
          { title: 'Fusiones y adquisiciones',    desc: 'Estructuración de transacciones, acuerdos de compraventa, garantías, cláusulas de ajuste y mecanismos de earn-out.' },
          { title: 'Due diligence',               desc: 'Revisiones legales completas para operaciones de M&A, financiamiento estructurado o reorganizaciones internas.' },
          { title: 'Acuerdos de accionistas',     desc: 'Pactos de sindicación, derechos de tag-along y drag-along, vetos, mecanismos de salida y resolución de conflictos.' },
          { title: 'Transformaciones societarias',desc: 'Cambios de tipo social, escisiones, fusiones, disoluciones y reorganizaciones con impacto en ingresos brutos y ganancias.' },
        ],
      },
      {
        key: 'aerocomercial',
        name: 'Aerocomercial',
        desc: 'Derecho aeronáutico, contratos de aviación, regulación de aerolíneas, seguros aéreos y representación ante la ANAC.',
        meetingTopic: 'derecho aerocomercial',
        intro: 'Práctica especializada en derecho aeronáutico y aerocomercial, con experiencia en regulación de aerolíneas, contratos de aviación, seguros y representación ante la ANAC y otras autoridades regulatorias del sector. Una de las áreas pilares del estudio desde 2015.',
        services: [
          { title: 'Derecho aeronáutico',         desc: 'Normativa aplicable a operadores aéreos, servicios aeroportuarios, transporte de carga y pasajeros y contratos vinculados a la aviación civil.' },
          { title: 'Contratos de aviación',       desc: 'Arrendamiento de aeronaves (dry lease, wet lease, ACMI), contratos de mantenimiento, handling y servicios de tierra.' },
          { title: 'Regulación de aerolíneas',    desc: 'Licencias, certificados de explotador (CESA), aprobaciones técnicas y operativas, y trámites de habilitación de rutas.' },
          { title: 'Seguros aéreos',              desc: 'Pólizas de cascos, responsabilidad civil aérea, war risk, asesoramiento en siniestros y reclamos internacionales.' },
          { title: 'Representación ante la ANAC', desc: 'Trámites administrativos, autorizaciones, infracciones y procedimientos sancionatorios ante la Administración Nacional de Aviación Civil.' },
        ],
      },
      {
        key: 'penal',
        name: 'Penal Económico',
        desc: 'Defensa penal en delitos económicos, lavado de activos, fraudes, corrupción corporativa y compliance penal preventivo.',
        meetingTopic: 'derecho penal económico',
        intro: 'Defensa penal en delitos económicos, lavado de activos, fraude, corrupción corporativa y compliance preventivo. Asesoramiento empresarial para minimizar la exposición a la responsabilidad penal de las personas jurídicas bajo la Ley 27.401.',
        services: [
          { title: 'Defensa penal económica',     desc: 'Asesoramiento desde la imputación inicial, pasando por la elevación a juicio, hasta la sentencia firme y eventuales recursos extraordinarios.' },
          { title: 'Lavado de activos',           desc: 'Defensa en investigaciones sobre operaciones sospechosas y prevención del lavado en sujetos obligados (escribanos, contadores, agentes financieros).' },
          { title: 'Fraude corporativo',          desc: 'Investigaciones internas, querellas, defensa de directivos y empresas en delitos contra el patrimonio y la administración fraudulenta.' },
          { title: 'Corrupción corporativa',      desc: 'Programas de integridad bajo Ley 27.401, defensa en cohecho, tráfico de influencias y negociaciones incompatibles con la función pública.' },
          { title: 'Compliance penal preventivo', desc: 'Diseño e implementación de programas de cumplimiento, capacitación, canales de denuncia, investigaciones internas y auditorías de integridad.' },
        ],
      },
    ],
  },
  team: {
    label: 'Equipo',
    title: 'Los socios y el equipo de asociados.',
    sub: 'Cada socio lidera una o dos áreas y coordina con el resto del equipo. El estudio suma asociados y un <a href="/contable" class="link-contable">equipo contable</a> integrado.',
    members: [
      { key: 'maria-ines-lertora',    initials: 'ML', name: 'María Inés Lértora',     role: 'Socia',     spec: 'Tributario · Penal Económico',                    photo: '/team/maria-ines-lertora.jpg' },
      { key: 'matias-pantarotto',     initials: 'MP', name: 'Matías Pantarotto',      role: 'Socio',     spec: 'Tributario · Penal Económico',                    photo: '/team/matias-pantarotto.jpg' },
      { key: 'maria-paz-bardagi',     initials: 'MB', name: 'María Paz Bardagí',      role: 'Socia',     spec: 'Aerocomercial · Administrativo Regulatorio',      photo: '/team/maria-paz-bardagi.jpg' },
      { key: 'maria-alejandra-rivero',initials: 'MR', name: 'María Alejandra Rivero', role: 'Asociada',  spec: 'Laboral · Societario',                            photo: '/team/maria-alejandra-rivero.jpg' },
      { key: 'german',                initials: 'GC', name: 'Germán Carballo',        role: 'Asociado',  spec: 'Tributario',                                      email: 'Gcarballo@pl-abogados.com',  photo: '/team/german.jpg' },
      { key: 'agustin',               initials: 'AZ', name: 'Agustín Zaballeta',      role: 'Asociado',  spec: 'Societario · Penal Económico',                    email: 'azaballeta@pl-abogados.com', photo: '/team/agustin.jpg' },
    ],
    ctaText: '',
  },
  timeline: {
    label: 'Trayectoria',
    title: 'Trayectoria',
    items: [
      { year: '2003', title: 'Fundación',         desc: 'Se constituye Pantarotto Lértora & Asocs. en Buenos Aires.' },
      { year: '2010', title: 'Red internacional', desc: 'Apertura de corresponsalías en distintos países.' },
      { year: '2015', title: 'Área aerocomercial',desc: 'La práctica aerocomercial se consolida como pilar del estudio.' },
      { year: '2020', title: 'División <a href="/contable" class="link-contable">contable</a>', desc: 'Incorporación del <a href="/contable" class="link-contable">área contable</a> integrada al servicio jurídico.' },
      { year: '2024', title: '20 años',           desc: 'Dos décadas asesorando a empresas nacionales e internacionales.' },
    ],
  },
  contact: {
    label: 'Contacto',
    title: 'Hablemos de',
    titleAccent: 'su caso',
    desc: 'Le ofrecemos una consulta inicial para evaluar su situación. Nuestro equipo le responderá dentro de las 24 horas hábiles.',
    formAreas: ['Tributario', 'Laboral', 'Societario', 'Aerocomercial', 'Penal Económico', 'Otro'],
  },
};
